language: java

jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"

services:
  - postgresql

script:
  - mvn clean install
  - mkdir spring-boot-app && cd spring-boot-app
  - mvn archetype:generate -DarchetypeGroupId=com.github.spring-boot-archetypes -DarchetypeArtifactId=spring-boot-quickstart -DarchetypeVersion=1.0.0 -DgroupId=com.company -DartifactId=webapp -Dversion=1.0.0 -DinteractiveMode=false
  - cd webapp && mvn clean test
  - cd ../.. && rm -rf webapp

notifications:
  email:
    on_success: change
    on_failure: always
